### ISSUE TITLE
Support for WebSite and Application smart alerts

### ISSUE THREAD

**Issue by francisra75** [gessnerfl/terraform-provider-instana#102]
Hello, we are extensively using both Website and Application smart alerts. 

We would like to know if you are planning to add support on this.

**Comment by gessnerfl** [comment]
Application alerts are already covered with #74. However as this feature is still in beta I want to wait until it is stable.
For website monitoring I will consider this ticket as a feature request to support web site alert settings and will consider ti for a future release.

**Comment by francisra75** [comment]
Thank you Florian, I will take a look. So then I should understand that those application alerts are what Instana considers calls "Smart Application Alert"?
I will test it to see how it works.

**Comment by gessnerfl** [comment]
Application smart alerts are now available with version 1.3.0

**Comment by gessnerfl** [comment]
Website smart alerts are now also available with version 1.4.0 (`instana_website_alert_config`)
Closing the ticket as the requested features are now available.

@francisra75 please open new ticket when feature is incomplete or if you face issues with the current implementation
