### ISSUE TITLE
Disable Built-in events

### ISSUE THREAD

**Issue by sccatch** [gessnerfl/terraform-provider-instana#105]
Hello,
as Instana a lot of built-in events are not applicable for us, we would like to disable built-in event via Terraform. Could you please help me with a way to disable built-in events?

Thanks

**Comment by gessnerfl** [comment]
I need to check how this can be implemented. Maybe a resource to manage the activation status of a built in event

**Comment by gessnerfl** [comment]
@sccatch This Terraform provider is now deprecated. I have handed the project over to IBM and the Instana development team now maintains the project here https://github.com/instana/terraform-provider-instana. Can you please open a ticket in this repository if the feature is still required?
