### ISSUE TITLE
 Instana Terraform provider has wrong documentation paths on registry.terraform.io

### ISSUE THREAD

**Issue by vatima2016** [gessnerfl/terraform-provider-instana#117]
It looks that the Instana Terraform provider has wrong documentation paths on _registry.terraform.io_.

For example **terraform-docs** generates links without _instana__ resource prefix in the resources documentation:

## Resources

| Name | Type |
|------|------|
| [instana_alerting_channel_pager_duty.rhsso](https://registry.terraform.io/providers/gessnerfl/instana/latest/docs/resources/alerting_channel_pager_duty) | resource |
| [instana_alerting_config.rhsso](https://registry.terraform.io/providers/gessnerfl/instana/latest/docs/resources/alerting_config) | resource |
| [instana_application_config.rhsso](https://registry.terraform.io/providers/gessnerfl/instana/latest/docs/resources/application_config) | resource |

It seems to be the right convention. See for example [cloudwatch_log_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_group): there is no _aws__ prefix in the last path fragment.

**Comment by gessnerfl** [comment]
Hi @vatima2016,

from my point of view everything looks fine. I check e.g. https://registry.terraform.io/providers/gessnerfl/instana/latest/docs/resources/instana_alerting_config and the `instana_` prefix is there.

Can you maybe share more details where you exactly face this issue? Or do you generate the documentation locally and run into this issue there?

**Comment by vatima2016** [comment]
Hi @gessnerfl,

the "right" URL should be https://registry.terraform.io/providers/gessnerfl/instana/latest/docs/resources/alerting_config
The prefix **_instana__** in the last path element should be "removed". What I mean is that the documentation should be organized a little bit other way on  https://registry.terraform.io 

See for example https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_group - they don't set prefix in the URL although  the resource name is **aws_cloudwatch_log_group**.

We use **terraform-docs** utility to generate documentation for  our Terraform projects. It creates links according to this convention (see example of the generated result above) and thus the links for the Instana TF provider's resources end up at the moment with 404 error.

**Comment by gessnerfl** [comment]
Hi @vatima2016,

thanks for clarifying. Also cross checked with the documentation and you are right. The files for the resources contain the `instana_` which is not in line with the documentation style guide (https://www.terraform.io/docs/registry/providers/docs.html#directory-structure).

**Comment by gessnerfl** [comment]
Fix is released with version v1.1.5
