### ISSUE TITLE
allow to skip certificate validation

### ISSUE THREAD

**Issue by carlobongiovanni** [gessnerfl/terraform-provider-instana#134]
Hi @gessnerfl , thanks for this amazing provider! On a self-hosted Instana environment, this provider fails unless the Instana CA is imported to the local keystore. For test reasons, would be nice if we could skip the certificate validation. Would you be willing to add it as a feature?

Thanks!

**Comment by gessnerfl** [comment]
@carlobongiovanni :  this also allows me to clean up parts of my test code. Will provide this feature soon

**Comment by carlobongiovanni** [comment]
thanks a lot @gessnerfl !
