### ISSUE TITLE
Make id not auto generated so I can pass it to instana_alerting_config

### ISSUE THREAD

**Issue by bmnidhin** [gessnerfl/terraform-provider-instana#138]
I have a terraform template with `instana_alerting_channel_pager_duty`, `instana_custom_event_spec_threshold_rule` and 
 `instana_alerting_config`.
 
Currently ids for eg `instana_alerting_channel_pager_duty` and `instana_custom_event_spec_threshold_rule` are auto generated by the code. So I have no option to pass ids to  `integration_ids` and `event_filter_rule_ids` other than hardcoding it in `instana_alerting_config`. So a human action is still needed to configure that step later.

```
resource "instana_alerting_config" "alertConfigPod" {
    integration_ids = ["hardcoded-id"] 
    event_filter_rule_ids = [ "hardcoded-id" ]
}

```
So please make an option to input id parameter to above resources and similar

is there any workaround for the same?

**Comment by gessnerfl** [comment]
@bmnidhin there is no workaround needed in this case. The id is available for each resource after apply.

Lets assume you have the following rules defined as Instana resources:

```hcl
resource "instana_custom_event_spec_threshold_rule" "my_threshold_rule" {
...
}

resource "instana_alerting_channel_pager_duty" "pd_alerting_channel" {
...
}
```

Then you can get the id by referring to the terraform resource as follows: 

```hcl
resource "instana_alerting_config" "alertConfigPod" {
    integration_ids = [ instana_alerting_channel_pager_duty.pd_alerting_channel.id ] 
    event_filter_rule_ids = [  instana_custom_event_spec_threshold_rule.my_threshold_rule.id ]
}
```

If the resources are in different terraform projects you can import them using remote states.

Hope this help.
