### ISSUE TITLE
 Application_alert_configuration Resource is duplicated each time terraform code is applied

### ISSUE THREAD

**Issue by alexluca2** [gessnerfl/terraform-provider-instana#141]
I am trying to configure application smart alerts for Instana using the resource “instana_application_alert_config”.
The issue is that each time I run the terraform code, the smart alerts are being created once again with a new id, even though the old ones are being recognized and their state is refreshed.
If a resource exists with a specific name, I would like only to apply the changes to it, or to refresh it’s state, not to create another one with the same name, but different id.

You can find the output from terraform plan/apply below: 

Step 1: the refresh part
instana_application_alert_config.smart_alert_testing_ro_traffic_drop[0]: Refreshing state... [id=cc31qlnp9i0q084maop0]
 
Step 2: the creation part
Terraform will perform the following actions:
 
  instana_application_alert_config.smart_alert_testing_ro_traffic_drop[0] will be created

The code used for it is the following:
* the variable rewards_deployment_list_ro is persistent, changes to the code are being done only the rule condition part.

resource "instana_application_alert_config" "smart_alert_testing_ro_traffic_drop" {
    count = length(var.rewards_deployment_list_ro)
    name              = "DigEna - ${var.rewards_deployment_list_ro[count.index]["name"]} μs - inbound_count_smart"
    description       = "DigEna - ${var.rewards_deployment_list_ro[count.index]["name"]} μs - inbound_count_smart "
    boundary_scope    = "INBOUND"
    severity          = "warning"
    triggering        = false
    include_internal  = false
    include_synthetic = false
    alert_channel_ids = [ instana_alerting_channel_pager_duty.rewards-production-pagerduty-channels_ro[count.index].id ]
    granularity       = 1800000
    evaluation_type   = "PER_AP"
    application {
        application_id = "${instana_application_config.ro_rewards-microservices-prod-app-config[count.index].id}"
        inclusive      = true
    }
    rule {
        throughput {
            metric_name = "calls"
            aggregation = "SUM"
        }
    }
    threshold {
        static {
            operator = "<="
            value    = 0
        }
    }
    time_threshold {
        violations_in_period {
            time_window = 1800000
            violations = 1
        }
    }   
}

After multiple runs of the code, in terraform state only the last created smart alerts appear, even though in Instana UI are present multiple resources with the same name.

**Comment by gessnerfl** [comment]
@alexluca2 I can confirm that I an repoduce the issue. Can you cross check if you get the same error message when adding/changing the given smart alert?

> Error: Provider produced inconsistent result after apply
>
> When applying changes to instana_application_alert_config.smart_alert_testing_ro_traffic_drop, provider
> "provider[\"registry.terraform.io/gessnerfl/instana\"]" produced an unexpected new value: Root resource was
> present, but now absent.
> 
>  This is a bug in the provider, which should be reported in the provider's own issue tracker.

**Comment by gessnerfl** [comment]
The root cause of this issue is the tag filter. For what ever reason Instana returns an empty AND expression when no tag filter is defined. I need to clarify this with Instana if this is the expected behaviour or a bug on their end. My expectation would be that `tagFilterExpression` in the json response is `null` in this case and not an empty AND expression. In general, I would consider an empty and expression as invalid.

**Comment by alexluca2** [comment]
@gessnerfl I added tag_filter, but still the smart alerts are being duplicated each time I run the code.

**Comment by alexluca2** [comment]
@gessnerfl thank you very much for your help. You were right, the fact that I was not using tag_filter was causing the alerts to be duplicated.

**Comment by gessnerfl** [comment]
@alexluca2 thanks for the confirmation. It is still considered as a bug. I'm in contact with Instana support to clarify the situation.

**Comment by gessnerfl** [comment]
@alexluca2: the issue is fixed with version 1.5.3
