### ISSUE TITLE
Add field ApplicationId on Synthetic Test resources

### ISSUE THREAD

**Issue by mbrizbee** [gessnerfl/terraform-provider-instana#160]
On Synthetic Test resource, it is possible to add the field applicationId to link a synthetic test at an application. This field is optional. 

https://instana.github.io/openapi/#section/Synthetic-Test-Properties:

applicationId Unique identifier of the Application Perspective.

**Comment by gessnerfl** [comment]
@mbrizbee I will consider this change for version 2.0.

**Comment by gessnerfl** [comment]
feature implemented with PR #161. Will be released with the upcoming release 2.x
