### ISSUE TITLE
Bug: Metric operator in Custom Event is missing the 'any' option

### ISSUE THREAD

**Issue by bhepburn** [gessnerfl/terraform-provider-instana#198]
When trying to build a new custom event, we were unable to specify the `any` metric operator.  

<img width="1026" alt="image" src="https://github.com/gessnerfl/terraform-provider-instana/assets/1223869/e60a34d0-7dbf-4a0d-a856-56f50333595c">

According to documentation `any` should be allowed:
https://github.com/gessnerfl/terraform-provider-instana/blob/main/docs/resources/custom_event_specification.md?plain=1#L252

UI also defines this as an option:
<img width="540" alt="image" src="https://github.com/gessnerfl/terraform-provider-instana/assets/1223869/77292cbe-dc29-417b-ae5b-9ea2010b3b9c">

**Comment by bhepburn** [comment]
Since this was a simple change, I created a PR.  Feel free to take it or close as you see fit:
https://github.com/gessnerfl/terraform-provider-instana/pull/199

**Comment by gessnerfl** [comment]
@bhepburn thanks for your contribution. I verified your change and it will be fixed with bugfix release 2.2.1
