### ISSUE TITLE
Add support to manage users

### ISSUE THREAD

**Issue by gessnerfl** [gessnerfl/terraform-provider-instana#2]
### Story
I want to be able to manage users through the terraform provider
So that I manage my users consistently through infrastructure as code

**Comment by gessnerfl** [comment]
For managing users the Instana REST API is not ideal for such automation tools. The main reason is that it first does not manage users as resource only but defines different end points to create (send invitation) and manage (delete, update). 
A create, sending an invitation, also does not return the user id although a user id is created. This makes it hard to manage the state in terraform. Invitations only operate on emails whereas users are managed with a user ID.
Because of this reasons this feature is not considered at the moment.

**Comment by ppuschmann** [comment]
This also will not become easier if you use external Auth-providers like Google-Login and then only want to define permissions for single users.

**Comment by gessnerfl** [comment]
I would also assume that corporates prefer using external Auth-providers and or SAML. It would make more sense to be able to manage group mappings for those external authentication providers instead of managing the users directly in Instana.

**Comment by ppuschmann** [comment]
External Auth providers: I'm with you.

But maybe you want to have some mapping between google-groups and roles.
So that all members of a group automatically are assigned to some role.

I guess this ^ is currently not solveable.

But it would be great some sort of manual mapping at the least in/with Terraform.

**Comment by gessnerfl** [comment]
But wouldn't you expect to configure such a mapping in instana. In case of SAML login I would expect to be able to map groups from the SAML assertion to roles in Instana. I don't think this feature is provided yet.

**Comment by gessnerfl** [comment]
@ppuschmann This Terraform provider is now deprecated. I have handed the project over to IBM and the Instana development team now maintains the project here https://github.com/instana/terraform-provider-instana. Can you please open a ticket in this repository if the feature is still required?
