### ISSUE TITLE
Incompatible provider version

### ISSUE THREAD

**Issue by pavan141994** [gessnerfl/terraform-provider-instana#200]
i am using terraform version v1.6.0
when i execute my terraform code i am getting below error

terraform init     

Initializing the backend...

Initializing provider plugins...
- Finding latest version of gessnerfl/instana...
╷
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/gessnerfl/instana v2.2.1 does not have a package available for your current platform,
│ windows_386.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other
│ versions of this provider may have different platforms supported.
╵

**Comment by gessnerfl** [comment]
@pavan141994 did it work with TF 1.5.x? Are you really working with windows 386 platform? Indeed I do not provide a 386 version but only AMD64 and ARM64.

**Comment by pavan141994** [comment]
it is working now
