### ISSUE TITLE
need some help on data element 

### ISSUE THREAD

**Issue by pavan141994** [gessnerfl/terraform-provider-instana#204]
Hi i would like to create multiple data elements for built events rather than going to add data element block i would like to put in a loop and pass the name and plugin id from json file and it should create data element for that
can you please help on this scenario?

**Comment by gessnerfl** [comment]
Hi @pavan141994,

this is a bit too generic to provide a detailed answer. In general terraform provides built in functions to decode json (https://developer.hashicorp.com/terraform/language/functions/jsondecode) and to read data from files (https://developer.hashicorp.com/terraform/language/functions/file). You can then use the built in for-expressions (https://developer.hashicorp.com/terraform/language/expressions/for) to map the data structure as needed or directly use the decoded json data in the `for_each` meta argument (https://developer.hashicorp.com/terraform/language/meta-arguments/for_each) to create a block of data elements

I hope this helps
