### ISSUE TITLE
Support for multiple Threshold Rules

### ISSUE THREAD

**Issue by pavan141994** [gessnerfl/terraform-provider-instana#206]
Can i have sample terraform code for ruleLogicalOperator with threshold rule type
it would be great if you help me on this?

**Comment by gessnerfl** [comment]
@pavan141994 this is currently not supported. But I will consider it for the next release.

**Comment by pavan141994** [comment]
Do we have terraform code available for custom event with multiple conditions?
currently we only had code available with single condition.
Please let me know

**Comment by Deepali-Surlikar** [comment]
@gessnerfl , can we get estimated date as to when the next release would happen?

**Comment by gessnerfl** [comment]
@Deepali-Surlikar At the moment, I can't give an ETA. I am currently maintaining the provider in my spare time. However, you can also contribute and implement the necessary changes if possible.

**Comment by gessnerfl** [comment]
@Deepali-Surlikar @pavan141994 feature is now available with version 2.3.0

**Comment by Deepali-Surlikar** [comment]
@gessnerfl , Thanks!!!

**Comment by debasisdas1976** [comment]
I am using version 2.4.1. I am trying to create multiple threshold rules for a custom event. But I get the following error

```
on main.tf line 71, in resource "instana_custom_event_specification" "threshold_custom_events":
71:     content {

No more than 1 "rules" blocks are allowed
```
Appreciate if you can share any sample code.
