### ISSUE TITLE
Allow up to 1024 rule-ids per instana_alerting_config

### ISSUE THREAD

**Issue by ppuschmann** [gessnerfl/terraform-provider-instana#39]
Instana Server (on-premise) supports more than six event_filter_rule_ids item per alert.

According to the API-documention the limit of rule-ids is 1024:
https://instana.github.io/openapi/#operation/putAlert

Example of the error:
`Error: event_filter_rule_ids: attribute supports 6 item maximum, config has 9 declared

  on main.tf line 229, in resource "instana_alerting_config" "alerting_test":
 229: resource "instana_alerting_config" "alerting_test" {`

**Comment by gessnerfl** [comment]
This seems to be a copy past bug ;) will merge the PR and provide a new release

**Comment by gessnerfl** [comment]
fixed with release 0.8.1
