### ISSUE TITLE
Add Event Type `agent_monitoring_issue`

### ISSUE THREAD

**Issue by gessnerfl** [gessnerfl/terraform-provider-instana#49]
Instana added an additional event type for alerts `agent_monitoring_issue`. Add this event type to the terraform provider.

**Comment by shashank-Jain-T-M** [comment]
Hello, we wanted to have application perspective to be added to instana_alerting_config.go,
how to go with that, can we get any help from here
Because i can see no argument under alert config so need to add that in your repo.

**Comment by gessnerfl** [comment]
@shashank-Jain-T-M please check #83
