### ISSUE TITLE
Add boundary scope to application configuration

### ISSUE THREAD

**Issue by gessnerfl** [gessnerfl/terraform-provider-instana#51]
Application configurations support the additional configuration of a `boundary_scope`. Add this field also to the terraform provider.

**Comment by jjtroberts** [comment]
+1

**Comment by gessnerfl** [comment]
@jjtroberts the new release 0.9.0 is now available. It is compatible with terraform version 0.12 and 0.13. The provider is now also available in the new public terraform registry: https://registry.terraform.io/providers/gessnerfl/instana/latest
