### ISSUE TITLE
Mocks are out of sync / readme does not match

### ISSUE THREAD

**Issue by martinei** [gessnerfl/terraform-provider-instana#71]
I tried to recreate the mocks following the readme and had no luck to recreate what is currently comitted. 
Also the existing generated mocks mention **instana/restapi/api.go**  which is no longer present since #35

**Comment by gessnerfl** [comment]
Was able to reproduce this. Seems that there were changes in gomock. Will further investigate

**Comment by gessnerfl** [comment]
Regenerated the mocks and updated the documentation. I was confused by my own documentation and the real usage of the tool. Added also a helper tool to simplify mocking.

**Comment by gessnerfl** [comment]
@martinei The changes are now merged to the master branch. Can you please crosscheck and close the ticket when everything works as expected?

**Comment by martinei** [comment]
This did indeed resolve my Problem. Thanks!
