### ISSUE TITLE
Add support to website monitoring

### ISSUE THREAD

**Issue by nullck** [gessnerfl/terraform-provider-instana#72]
You are doing a great work @gessnerfl   thank you.

Would be nice the terraform resource in order to also create the websites configurations - https://instana.github.io/openapi/#tag/Website-Configuration

**Comment by gessnerfl** [comment]
I also already planned to support this. It is not a big deal to add this to the terraform provider. What I would miss in this case is the authentication token for the application. In the UI you would just get it from the snippet. The API does not provide this information. This is a major block to automate the creation of web site monitoring together with the application end to end.

@nullck is this feature interesting for you also without having this information available?

**Comment by gessnerfl** [comment]
Feature is available with version 0.10.0
