### ISSUE TITLE
Match Specification for Application Configuration is to strict

### ISSUE THREAD

**Issue by martinei** [gessnerfl/terraform-provider-instana#75]
I need to create an "instana_application_config" with 

match_specification = "kubernetes.pod.label.foo/bar EQUALS 'blub'"

The "/" is not allowed by the plugin.  [This Regex](https://github.com/gessnerfl/terraform-provider-instana/blob/master/instana/filterexpression/filter-expression-parser.go#L112) should also allow "/".

Instana itself has not problem with "/"  beeing part of the label name.

**Comment by gessnerfl** [comment]
Fix is released with version 0.9.2

**Comment by martinei** [comment]
Thanks a lot!
