### ISSUE TITLE
Support to manage Synthetic endpoints

### ISSUE THREAD

**Issue by gessnerfl** [gessnerfl/terraform-provider-instana#78]
# Story
I want to be able to configure synthetic endpoints 
So that I can manage synthetic endpoint configurations consistently across tenants

# Technical Details
Synthetic endpoints are managed globally within a tenant (Applications -> Services -> Configure Services -> Synthetic Endpoints. To provide an option to configure this endpoints also through infrastructure code the provider should be extended by this feature.
https://instana.github.io/openapi/#operation/getSyntheticCalls

**Comment by jonassiefker** [comment]
All synthetic endpoints are managed globally with single requests, which would require lists of nested objects in the terraform resource. There currently does not seem to be a feasible way to do this.

**Comment by gessnerfl** [comment]
Closing due to  limited API capabilities
