### ISSUE TITLE
Application perspetive to be added as arguments.

### ISSUE THREAD

**Issue by shashank-Jain-T-M** [gessnerfl/terraform-provider-instana#83]
Hey @gessnerfl doing great work,
wanted to have application perspective to be added to instana_alerting_config,
Because i can see no argument under alert config so need to add that in your repo to support adding application perspective for our alerts.
we are able to use DFQ,all entities option, but not the Application perspective.
how to go with that, can we get any help from here

**Comment by gessnerfl** [comment]
@shashank-Jain-T-M configuring alerting based on applications is a UI feature. On API level applications are also expressed by DFQ:
`entity.application.id:\"my-application-perspective-id\""`
If you configure your application perspectives also with the TF provider you can use terraform interpolation syntax.

**Comment by gessnerfl** [comment]
I will add this also to the documentation.

**Comment by shashank-Jain-T-M** [comment]
Thanks a lot for the clarification, much needed one.

**Comment by gessnerfl** [comment]
Documentation adjusted with version 0.10.0

**Comment by shashank-Jain-T-M** [comment]
Do we have any option to add builtin events in terraform?

**Comment by shashank-Jain-T-M** [comment]
if yes, can i get the Document or the syntax for the same

**Comment by gessnerfl** [comment]
@shashank-Jain-T-M: can you please open a new issue for this topic and describe what you want to do with the builtin events?
