### ISSUE TITLE
Support Builtin Events as a data source e.g. for built in events

### ISSUE THREAD

**Issue by shashank-Jain-T-M** [gessnerfl/terraform-provider-instana#86]
We wanted to add builtin events that exist in instana to the alerts that are managed by terraform.
as i could see there is no entity to add via DFQ
So can you help me with a way to add builtin events for alerts created terraform

**Comment by gessnerfl** [comment]
@shashank-Jain-T-M: So far there is no native implementation for built in events available. I will consider this as a feature request. Built in events will be provided as a data source in future.

For the time being you could query the id of the builtin event manually through the API (` https://<your-account>.instana.io/api/events/settings/event-specifications/built-in`) and use the ID in the terraform code. This is not nice but can be used as a workaround until the data source is available.

**Comment by shashank-Jain-T-M** [comment]
I have got the Id for that event.
but how do i add that in my terraform code, as DFQ(entity.event.id:<eventid>)?
This step need to be known if available.

**Comment by gessnerfl** [comment]
@shashank-Jain-T-M 
My understanding is that you want to configure built in events in alerts. Alerts are configured in the terraform instana provider through the resource `instana_alerting_config`. In this resource you can either configure event types or specific events (field `event_filter_rule_ids`). The field contains the ID of custom and/or builtin events. You can enter the id in this list. For sure you can also mix this with references to fields of resources (such as custom event configurations).
Hope this helps.

**Comment by gessnerfl** [comment]
Feature will be released with the upcoming release 0.11.0. Changes already merged to master.

**Comment by gessnerfl** [comment]
Release 0.11.0 is now available
