### ISSUE TITLE
release 0.10.0 with mismatching checksums/SHA

### ISSUE THREAD

**Issue by ppuschmann** [gessnerfl/terraform-provider-instana#88]
Using Terraform 0.14.4 I got this error on 2020-02-02 14:45 UTC
(if this is a caching issue or similar)

```
Initializing the backend...

Initializing provider plugins...
- Finding gessnerfl/instana versions matching "0.10.0"...
- Installing gessnerfl/instana v0.10.0...
Error: Failed to install provider

Error while installing gessnerfl/instana v0.10.0: checksum list has unexpected
SHA-256 hash a37c4f79c5a1d926486ebb66a27f2ecc547d868cb1c17f92107a5b3196a93783
(expected da9ab5cc67035d6500a6e764ba466c0e69662eae7fd959f132563c4cbfb17701)
```

```hcl
terraform {
  required_providers {
    instana = {
      source  = "gessnerfl/instana"
      version = "0.10.0"
    }
  }
  required_version = ">= 0.13"
}
```

**Comment by gessnerfl** [comment]
It seems that there is an issue in the release 0.10.0 of the provider. I had to rerun the build and with this the artifacts and the checksums modified. However this modification was not synchronized to the terraform registry. A resync from terraform registry also did not solve the issue.
I provided a new patch release 0.10.1 which is now working fine on my machine.

Can you please cross check @ppuschmann

**Comment by ppuschmann** [comment]
Version 0.10.0 seems to be not recoverable.

For version 0.10.1 everything is fine!
