### ISSUE TITLE
Add support to manage groups

### ISSUE THREAD

**Issue by gessnerfl** [gessnerfl/terraform-provider-instana#93]
# Story
I want to be able to manage user groups as a replacement for resource instana_user_role
So that I again can manage the permission of groups in the terraform provider

**Comment by ac427** [comment]
@gessnerfl , I see 1.0.0 is out and I don' see manage groups in instana documentation? Just checking if it is something coming soon or missing in docs?

**Comment by gessnerfl** [comment]
@ac427 It is not included in version 1.0.0 but it is still planned to be implemented.
