### ISSUE TITLE
invalid preface while using terraform provider for imports and creating slack channel

### ISSUE THREAD

**Issue by suraj2410** [gessnerfl/terraform-provider-instana#99]
terraform 0.14.7

**provider config:**
``` 
terraform {

  required_version = ">= 0.14.7"

  required_providers {
    instana = {
      source = "gessnerfl/instana"
      version = "1.0.0"
    }
  } 

provider "instana" {
  api_token = "xxxxxxxxxxxx"
  endpoint = "xxx.instana.io"
  default_name_prefix = ""
  default_name_suffix = ""
}
```
**resource creation**

```
resource "instana_alerting_channel_slack" "slack_test" {
  name        = "test"
  webhook_url = https://xxxxxxxxxx
  channel     = "test_channel"
```

Plan works fine and upon first apply i get:

```
instana_alerting_channel_slack_test: Creating...

Error: failed to send HTTP PUT request to Instana API; status code = 0; status message = ; Headers map[], Put "https://xxx.instana.io/api/events/settings/alertingChannels/xxxxxxxxxxx": net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x01\x01\x18\a\x01\x01\x01\x01\x01\x01\x00\x00\x00\x00\x00\x00\x01invalid_preface"

  on main.tf line 1, in resource "instana_alerting_channel_slack" "slack_test":
   1: resource "instana_alerting_channel_slack" "slack_test" {

```

The token has access to Events.

Any ideas?

**Comment by gessnerfl** [comment]
@suraj2410 I think your provider configuration is wrong. As described in the documentation the endpoint should be `<tenant>-<org>.instana.io` without `https://` in front

**Comment by suraj2410** [comment]
@gessnerfl am sorry i also tried with the correct URL and also updated the endpoint in the initial question but it still doesnt work

**Comment by suraj2410** [comment]
@gessnerfl my bad now it works.. thank you :)

**Comment by gessnerfl** [comment]
@suraj2410 great to hear that the issue is resolved.

**Comment by kayahk** [comment]
Hi there,
I am also facing this issue and believe my provider configuration is correct. We are deploying (plan + apply) from a central pipeline repository and including modules from another repo. This the error message in the pipeline:
```
Error: failed to send HTTP GET request to Instana API; status code = 0; status message = ; Headers map[], Get "https://xxxxxxxxxxxxxx.instana.io/api/events/settings/alertingChannels/c7xxxxxxxxxxxxxxpg": net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x00\x00\x17\a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01invalid_preface"
│ 
│   with module.instana[0].instana_alerting_channel_email.instana_email,
│   on .terraform/modules/instana/instana/main.tf line 39, in resource "instana_alerting_channel_email" "instana_email":
│   39: resource "instana_alerting_channel_email" "instana_email" {
```
I omitted the identical message for other resources that are in the plan. The provider config is this:

deployment repository:
```
provider "instana" {
  endpoint  = var.instana_agent_endpoint
  api_token = var.instana_agent_key
}
```

module repository:
```
terraform {
  required_providers {
    instana = {
      source  = "gessnerfl/instana"
      version = "1.2.0"
    }
  }
}
```

Any idea what I'm missing here?
Thanks!

**Comment by kayahk** [comment]
ok, sorry for the confusion. I obviously did miss the part where you state `As described in the documentation the endpoint should be <tenant>-<org>.instana.io ` 
So, I changed the `api_endpoint` in the provider configuration which lead to a different error message like here:
```
Error: failed to send HTTP GET request to Instana API; status code = 403; status message = 403 Forbidden
Body: {"errors":["Insufficient access rights for resource. Missing permissions: canConfigureIntegrations"]}
```

Looks like another issue and not related to this one.

**Comment by gessnerfl** [comment]
@kayahk this is an issue related to you api token. Make sure that you have configured the required permissions for the used api token. In this case the permission to configure Integrations/Alerting Channels is missing
